Add put/delete functions to auth and audit
djzort/perl-WebService-HashiCorp-Vault pull request #12
Opened 2022-10-29 12:47 UTC by yewtc

This a result of the Pull Request Club. A small step on the way. I can see lots of other stuff to do but I have confined myself to just adding put and delete functions to auth and audit. I chose 'put' rather that 'post' as the former seems closer to the REST idea, though the API spec says that they are equivalent - at least for now (both work).

2023-01-05 23:57 UTC, 0x1F602 requested changes

2023-01-05 23:57 UTC, 0x1F602 commented on lib/WebService/HashiCorp/Vault/Sys.pm
> +    return $self-_sys_put( 'audit', $name, %params );
found a bug

2023-01-05 23:57 UTC, 0x1F602 commented on lib/WebService/HashiCorp/Vault/Sys.pm
> +    return $self-_sys_del( 'audit', $name );
bug ->

2023-01-06 14:44 UTC, yewtc commented
Dumb error fixed.  I guess I made a last minute change - and didn't check it still worked. My bad.

2023-01-13 08:46 UTC, merged